### PR TITLE
Fix wtsi signon errors

### LINKED ISSUE #93: DPL-011 - Update Client API
Client changes for:
Describe the Housekeeping
Sanger used to provide a single-sign-on service, which set a WTSISignOn cookie. This was used by Sequencescape to provide an alternative authentication process to LDAP.

This service has been retired, however we still occasionally see users who have this cookie set. My suspicion is that another group in Sanger is setting it to avoid needing to update their logon process.

We should:

Remove code from Sequencescape that checks this cookie. If I recall correctly we might have also allowed user API keys to be provided in this cookie. So this change might have some impact on any users of out v1 API. (Although gut says no, might be good to see if we can extract this from our logs)

sequencescape_client_api has some code to handle passing through the information. We can definitely strip this out.

There are some mitigations in the connection_options configurations of limber/gatekeeper which attempt to prevent the pass-through of the cookie by defining their own 'cookie' key. However given recent exceptions it appears these aren't working as intended. Anyway, these live in the deployment project, and should probably also be removed.

### PR DESCRIPTION
**Pull request by JamesGlover**
Closes #93

Changes proposed in this pull request:

* Remove reading of WTSISignOn cookie
* Rename field to user API key
* Bump to 0.6.0 (as potentially breaking change) 
* Add GH action
* Add talismanrc to gitignore

### CODE REVIEW

File: lib/sequencescape-api/version.rb [hunk 1]
```diff
@@ -1,5 +1,5 @@
 module Sequencescape
   class Api
-    VERSION = '0.5.0'.freeze
+    VERSION = '0.6.0-rc1'.freeze
```
Comment (KatyTaylor) [inline lib/sequencescape-api/version.rb:3]: Shouldn't a potentially breaking change be a major version? -> 1.0.0 ?

File: .talismanrc [hunk 2]
```diff
@@ -0,0 +1,45 @@
+fileignoreconfig:
```
Comment (KatyTaylor) [inline .talismanrc:1]: Phil had a suggested workflow where we don't commit these. 

 I think it made sense, because if these files are changed, the checksum will be different, so Talisman will flag them again. So you don't gain anything from committing this. The alternative is to review the things it flags, and then ignore it locally using git commit --no-verify. 

I will try to find his post though.

Comment (KatyTaylor) [reply .talismanrc:1]: Hmm I think probably post was too long ago for Slack to have it.

File: .github/workflows/ruby.yml [hunk 3]
```diff
@@ -0,0 +1,39 @@
+name: Ruby
```
Comment (KatyTaylor) [inline .github/workflows/ruby.yml:1]: Well done for setting this up. Was it still on Travis, or no CI?

File: lib/sequencescape-api/connection_factory/actions.rb [hunk 4]
```diff
@@ -151,7 +151,7 @@ def parse_json_from(response)
   private :parse_json_from
 
   def headers
-    { 'Accept' => 'application/json', 'Cookie' => "WTSISignOn=#{cookie}" }.tap do |standard|
+    { 'Accept' => 'application/json', 'Cookie' => "api_key=#{user_api_key}" }.tap do |standard|
```
Comment (KatyTaylor) [inline lib/sequencescape-api/connection_factory/actions.rb:154]: Apologies, never looked at this code before. Is this is the bit that defines the headers that are passed in requests to Sequencescape?
Will Sequencescape know what to do with a cookie called `api_key`?

File: lib/sequencescape-api/rails.rb [hunk 5]
```diff
@@ -26,7 +25,7 @@ def api_class
     private :api_class
 
     def configure_api
-      @api = api_class.new({ cookie: cookies['WTSISignOn'] }.merge(api_connection_options))
+      @api = api_class.new(api_connection_options)
```
Comment (KatyTaylor) [inline lib/sequencescape-api/rails.rb:28]: `api_connection_options` is just an empty hash, defined below in `def api_connection_options` ?

File: lib/sequencescape-api/connection_factory.rb [hunk 6]
```diff
@@ -7,8 +7,8 @@ class Sequencescape::Api::ConnectionFactory
 
   def self.create(options)
```
Comment (KatyTaylor) [inline lib/sequencescape-api/connection_factory.rb:8]: Where is this method called from?

File: lib/sequencescape-api/version.rb (hunk 1 above)
Comment (JamesGlover) [reply lib/sequencescape-api/version.rb:3]: General semver rules only apply after you hit version 1. Before v1 the second digit generally indicates a breaking change. TBH, we should probably just jump to version 1, no real reason to do a perpetual beta.

File: .talismanrc (hunk 2 above)
Comment (JamesGlover) [reply .talismanrc:1]: Ahhh, no, my fault. I was aware of that proposal but added this accidentally. Will fix.

File: .github/workflows/ruby.yml (hunk 3 above)
Comment (JamesGlover) [reply .github/workflows/ruby.yml:1]: No CI at all.

File: lib/sequencescape-api/connection_factory/actions.rb (hunk 4 above)
Comment (JamesGlover) [reply lib/sequencescape-api/connection_factory/actions.rb:154]: Yep, Sequencescape has had a fallback to API key for several years now.

File: lib/sequencescape-api/rails.rb (hunk 5 above)
Comment (JamesGlover) [reply lib/sequencescape-api/rails.rb:28]: Its the responsibility of the application including sequencescape_client_api to implement this, although it would probably make more sense to throw an exception explaining this. Will change.

File: lib/sequencescape-api/connection_factory.rb (hunk 6 above)
Comment (JamesGlover) [reply lib/sequencescape-api/connection_factory.rb:8]: https://github.com/JamesGlover/sequencescape-client-api/blob/087bbd8d29359c56272e2ba9bcd36c72f06aa048/lib/sequencescape-api/core.rb#L16

Comment (JamesGlover) [reply lib/sequencescape-api/connection_factory.rb:8]: Ugh, last time I tried that it did a nice inline preview.

Comment (JamesGlover) [reply lib/sequencescape-api/connection_factory.rb:8]: Ahh, needs to be the same repo

File: .talismanrc (hunk 2 above)
Comment (JamesGlover) [reply .talismanrc:1]: Ahh, looks like I added it to git ignore, but forgot to remove it from the commits

File: lib/sequencescape-api/version.rb (hunk 1 above)
Comment (KatyTaylor) [reply lib/sequencescape-api/version.rb:3]: Oh that's odd, didn't know that! Do you know the reason for it?

File: lib/sequencescape-api/connection_factory.rb (hunk 6 above)
Comment (KatyTaylor) [reply lib/sequencescape-api/connection_factory.rb:8]: Ah thanks, I was searching for `Sequencescape::Api::ConnectionFactory.create`

File: lib/sequencescape-api/rails.rb (hunk 5 above)
Comment (KatyTaylor) [reply lib/sequencescape-api/rails.rb:29]: Thanks

**Review by KatyTaylor — APPROVED** [review]

File: lib/sequencescape-api/version.rb (hunk 1 above)
Comment (JamesGlover) [reply lib/sequencescape-api/version.rb:3]: Its mostly to allow version numbers before 1.0 to indicate expected instability in the API, so you can iterate quickly until you've got something that feels solid. Unless you mean its odd that we haven't gone 1.0, in which case there's no particular reason, just never taken the step. And given we're slowly migrating over to API 2.0, it feels a little odd to do it now.
